# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.treat_symbols_as_metadata_keys_with_true_values = true
  config.run_all_when_everything_filtered = true
  config.filter_run :focus

  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'
end

require "httpserver"

def port
  5001
end

def start_http_server(port)
  server = HTTPServer.new(port)
  server.create_server
  calling_thread = Thread.current
  Thread.new {
    begin
      server.accept_loop
    rescue Exception => e
      calling_thread.raise(e)
    end
  }
  server
end

def client_send(uri)
  socket = TCPSocket.new("localhost", port)
  socket.write("GET #{uri} HTTP/1.0\r\n\r\n")
  content = timeout(0.3) { socket.read }
  socket.close
  content
end

